[build-system]
requires = ["flit_core >= 3.4"]
build-backend = "flit_core.buildapi"

[project]
name = "roxie"
version = "0.0.1"
authors = [{name = "Vittorio La Barbera"}]
description = "A Python package for RL control of musculoskeletal systems"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "jax",
  "chex",
  "optax",
  "flax",
  "distrax",
  "hydra-core",
  "playground",
  "termcolor",
  "flashbax"
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[project.optional-dependencies]
test = ["pytest"]


[tool.ruff.lint]
ignore = ["C901", "E501", "E741", "F402", "F823", "E402", "E731" ]
select = ["C", "E", "F", "I", "W"]