# @package _global_


# The defaults list tells Hydra how to build the final config.
defaults:
  - agent: ddpg      # Load `ddpg.yaml` from the `agent/` dir into the `agent` key.
  - model: mlp     # Load `mlp.yaml` from the `model/` dir into the `network` key.
  - noise: ou
  - _self_           # Allows this file to add its own values, too.

seed: 0
parallel_envs: 400

env:
  # Default parameters
  env_name: AcrobotSwingup # CartpoleBalance
  list_envs: false

# Hydra configuration for logging and output directories
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
