name: "ddpg"
gamma: 0.99
tau: 0.005
learning_rate_actor: 1e-4
learning_rate_critic: 1e-3

buffer_size: 1_000_000
batch_size: 256
batch_iterations: 50
steps_before_batches: 1e4
steps_between_batches: 50