name: "ddpg"

args: 
  gamma: 0.99
  tau: 0.005
  actor_learning_rate: 1e-3
  critic_learning_rate: 1e-3
  exploration_noise: 0.1
  steps_before_learning: 1000
  memory_warmup: 1000
  steps_between_updates: 500
  learning_steps: 150

memory:
  _target_: replays.buffer.JaxReplayBuffer
  
  capacity: 10_000_000
  batch_size: 256
