# @package _global_

env:
  # Default parameters
  seed: 0
  parallel_envs: 800
  env_name: WalkerWalk # CartpoleBalance
  list_envs: false

# The defaults list tells Hydra how to build the final config.
defaults:
  # - agent: ppo      # Load `ddpg.yaml` from the `agent/` dir into the `agent` key.
  - agent: ddpg
  - noise: ou
  - _self_           # Allows this file to add its own values, too.

# Hydra configuration for logging and output directories
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
