# @package _global_


# The defaults list tells Hydra how to build the final config.
defaults:
  - agent: ppo      # Load `ddpg.yaml` from the `agent/` dir into the `agent` key.
  # - noise: ou
  - _self_           # Allows this file to add its own values, too.

seed: 0
parallel_envs: 100

env:
  # Default parameters
  env_name: WalkerWalk # CartpoleBalance
  list_envs: false

# Hydra configuration for logging and output directories
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
